Room state
niklaslong/matrix-client pull request #14
Opened 2020-09-24 16:47 UTC by fancycade

We should merge #13 before this.

This PR addresses #7 and #11.

2020-09-25 07:48 UTC, niklaslong commented
Looks like #13 introduced some conflicts, @fancycade could you rebase?

2020-09-25 14:19 UTC, fancycade commented
Oops didnt realize the log would be that screwed up. Good thing this is an experiment :rofl:

2020-09-27 13:13 UTC, niklaslong requested changes
Great work—I've left a few comments. Once this is merged I'll review the project and its status in relation to the SDK.

2020-09-27 13:13 UTC, niklaslong commented on lib/matrix_client.ex
> +  defp joined_rooms_helper(session, room_ids) do
How about something more descriptive, perhaps `map_joined_rooms` or `list_joined_rooms`?

2020-09-27 13:13 UTC, niklaslong commented on lib/matrix_client.ex
> +    new_id =
As an aside, I'm seeing the following block a lot—refactor opportunity in future.

2020-09-27 13:13 UTC, niklaslong commented on lib/matrix_client/session.ex
> +      %{url: url, rooms: %{}, invites: %{}, aliases: %{ids: %{}, aliases: %{}}}
What are the `ids` in the `aliases` map?

2020-09-27 13:13 UTC, niklaslong commented on lib/matrix_client/session.ex
> +  defp alias_helper_ids(aliases, room_id, a) do
Not sure what these functions are doing just by reading the name? In general I'm not a big fan of using `helper` as a descriptor as it's so vague. Thoughts?

2020-09-30 20:59 UTC, fancycade commented
@niklaslong Updated based on feedback.

Changed any helper names or refactored.

Moved ids into its own map. The reason for it  is that internally there are times to translate an alias to an id, and then the alias map is to translate an id to an alias (typically for external reasons like listing joined rooms). Can't decide if the naming is backwards or not :laughing:

2020-10-02 19:34 UTC, niklaslong approved these changes

2020-10-02 19:34 UTC, merged